services:
  app:
    build:
      target: dependencies
    environment:
      NODE_ENV: development
    command: npm run dev
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: support_app_node_modules
        target: /app/node_modules
    ports:
      - "3001:3001"
      - "5173:5173"

volumes:
  support_app_node_modules:
